### ISSUE TITLE
How to run this app on android , app structure is confusing to me .

### ISSUE THREAD

**Issue by purushottam858** [RobertFlatt/Android-for-Python#2]
I finally made apk out of it and run it on mobile .
But where the images and videos are stored , I did not find the pictures and videos in gallery or anywhere on my android device .

THIS IS GETTING PRINTED ON THE TERMINAL WHEN I CLICK TO CAPTURE THE IMAGE .

03-02 00:29:30.138  7536  7536 I python  :  Traceback (most recent call last):
03-02 00:29:30.139  7536  7536 I python  :    File "jnius/jnius_proxy.pxi", line 50, in jnius.jnius.PythonJavaClass.invoke
03-02 00:29:30.139  7536  7536 I python  :    File "jnius/jnius_proxy.pxi", line 76, in jnius.jnius.PythonJavaClass._invoke
03-02 00:29:30.140  7536  7536 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/app/cameraxf/listeners.py", line 94, in onClick
03-02 00:29:30.140  7536  7536 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/app/cameraxf/cameraxf.py", line 216, in photo_take
03-02 00:29:30.141  7536  7536 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/app/cameraxf/camerax.py", line 286, in photo_take
03-02 00:29:30.148  7536  7536 I python  :  AttributeError: type object 'android.provider.MediaStore$MediaColumns' has no attribute 'RELATIVE_PATH'
03-02 00:29:30.349  7536  7536 I python  :  Traceback (most recent call last):
03-02 00:29:30.351  7536  7536 I python  :    File "jnius/jnius_proxy.pxi", line 50, in jnius.jnius.PythonJavaClass.invoke
03-02 00:29:30.352  7536  7536 I python  :    File "jnius/jnius_proxy.pxi", line 76, in jnius.jnius.PythonJavaClass._invoke
03-02 00:29:30.353  7536  7536 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/app/cameraxf/listeners.py", line 94, in onClick
03-02 00:29:30.355  7536  7536 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/app/cameraxf/cameraxf.py", line 216, in photo_take
03-02 00:29:30.356  7536  7536 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/app/cameraxf/camerax.py", line 286, in photo_take
03-02 00:29:30.357  7536  7536 I python  :  AttributeError: type object 'android.provider.MediaStore$MediaColumns' has no attribute 'RELATIVE_PATH'
03-02 00:29:30.526  7536  7536 I python  :  Traceback (most recent call last):
03-02 00:29:30.527  7536  7536 I python  :    File "jnius/jnius_proxy.pxi", line 50, in jnius.jnius.PythonJavaClass.invoke
03-02 00:29:30.527  7536  7536 I python  :    File "jnius/jnius_proxy.pxi", line 76, in jnius.jnius.PythonJavaClass._invoke
03-02 00:29:30.527  7536  7536 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/app/cameraxf/listeners.py", line 94, in onClick
03-02 00:29:30.528  7536  7536 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/app/cameraxf/cameraxf.py", line 216, in photo_take
03-02 00:29:30.528  7536  7536 I python  :    File "/home/purushottam2/Desktop/any_where/AW/aw/.buildozer/android/app/cameraxf/camerax.py", line 286, in photo_take

**Comment by RobertFlatt** [comment]
What api version was used to build this apk ?
https://github.com/RobertFlatt/Android-for-Python/blob/main/cameraxf/BUILDOZER_README.txt#L25

When the api is changed remember to do a _buildozer appclean_
