### ISSUE TITLE
storage example crashing on android 8

### ISSUE THREAD

**Issue by Sahil-pixel** [RobertFlatt/Android-for-Python#3]
03-14 15:00:01.701 24103 24169 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
03-14 15:00:01.765 24103 24169 I python  : [INFO   ] [Text        ] Provider: sdl2
03-14 15:00:02.017 24103 24169 I python  :  Traceback (most recent call last):
03-14 15:00:02.017 24103 24169 I python  :    File "/home/sahil/apps/.buildozer/android/app/main.py", line 11, in <module>
03-14 15:00:02.018 24103 24169 I python  :    File "/home/sahil/apps/.buildozer/android/app/storage.py", line 13, in <module>
03-14 15:00:02.018 24103 24169 I python  :    File "/home/sahil/apps/.buildozer/android/platform/build-arm64-v8a/build/python-installs/storage/jnius/reflect.py", line 208, in autoclass
03-14 15:00:02.019 24103 24169 I python  :    File "jnius/jnius_export_func.pxi", line 28, in jnius.jnius.find_javaclass
03-14 15:00:02.020 24103 24169 I python  :  jnius.jnius.JavaException: Class not found b'android/provider/MediaStore$Downloads'
03-14 15:00:02.020 24103 24169 I python  : Python for android ended.

**Comment by RobertFlatt** [comment]
The Android storage database is not compatible for api < 28, use file operations.

I think could add a graceful fallback to file operations, but I have not looked at the implications for the two Uri methods. Would this be of interst to you?

**Comment by RobertFlatt** [comment]
Now with added support for devices with device api = 21 thru api = 28
