### ISSUE TITLE
webview app crashes during pause and resume app

### ISSUE THREAD

**Issue by Sahil-pixel** [RobertFlatt/Android-for-Python#4]
3-14 15:09:03.998 28571 28610 I python  : [INFO   ] [GL          ] Texture max size <16384>
03-14 15:09:03.998 28571 28610 I python  : [INFO   ] [GL          ] Texture max units <16>
03-14 15:09:04.035 28571 28610 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
03-14 15:09:04.037 28571 28610 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
03-14 15:09:04.056 28571 28610 I python  : [INFO   ] [Text        ] Provider: sdl2
03-14 15:09:08.200 28571 28610 I python  : [WARNING] [Base        ] Unknown <android> provider
03-14 15:09:08.201 28571 28610 I python  : [INFO   ] [Base        ] Start application main loop
03-14 15:09:08.206 28571 28610 I python  : [INFO   ] [GL          ] NPOT texture support is available
03-14 15:09:19.857 28571 28610 I python  : [INFO   ] [Base        ] Leaving application in progress...
03-14 15:09:19.859 28571 28610 I python  :  Traceback (most recent call last):
03-14 15:09:19.860 28571 28610 I python  :    File "/home/sahil/apps/.buildozer/android/app/main.py", line 81, in <module>
03-14 15:09:19.862 28571 28610 I python  :    File "/home/sahil/apps/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/storage/kivy/app.py", line 950, in run
03-14 15:09:19.864 28571 28610 I python  :    File "/home/sahil/apps/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/storage/kivy/base.py", line 582, in runTouchApp
03-14 15:09:19.866 28571 28610 I python  :    File "/home/sahil/apps/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/storage/kivy/base.py", line 347, in mainloop
03-14 15:09:19.873 28571 28610 I python  :    File "/home/sahil/apps/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/storage/kivy/base.py", line 387, in idle
03-14 15:09:19.880 28571 28610 I python  :    File "/home/sahil/apps/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/storage/kivy/clock.py", line 733, in tick
03-14 15:09:19.887 28571 28610 I python  :    File "/home/sahil/apps/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/storage/kivy/clock.py", line 776, in post_idle
03-14 15:09:19.888 28571 28610 I python  :    File "kivy/_clock.pyx", line 616, in kivy._clock.CyClockBase._process_events
03-14 15:09:19.892 28571 28610 I python  :    File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
03-14 15:09:19.901 28571 28610 I python  :    File "kivy/_clock.pyx", line 645, in kivy._clock.CyClockBase._process_events
03-14 15:09:19.906 28571 28610 I python  :    File "kivy/_clock.pyx", line 203, in kivy._clock.ClockEvent.tick
03-14 15:09:19.907 28571 28610 I python  :    File "kivy/_clock.pyx", line 120, in kivy._clock.ClockEvent.get_callback
03-14 15:09:19.908 28571 28610 I python  :    File "/home/sahil/apps/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/storage/kivy/weakmethod.py", line 45, in __call__
03-14 15:09:19.909 28571 28610 I python  :  AttributeError: 'WebView' object has no attribute 'f2'
03-14 15:09:19.909 28571 28610 I python  : Python for android ended.

**Comment by RobertFlatt** [comment]
Thanks for the great testing.
I can replicate this one, will update when I have a resolution.

**Comment by RobertFlatt** [comment]
Resolved, and updated in github.  Only webview.py changed.
Thank you for finding this.

**Comment by Sahil-pixel** [comment]
Great work ... please Work more on Android ....We need a well bridge to implement python Kivy application for Android ...

**Comment by RobertFlatt** [comment]
Thanks.
And yes, I agree.
