### ISSUE TITLE
share recv app video file not playing 

### ISSUE THREAD

**Issue by Sahil-pixel** [RobertFlatt/Android-for-Python#6]
testing android 8
03-22 13:05:37.556 14966 14989 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
03-22 13:05:38.283 14966 14989 I python  : [WARNING] [Base        ] Unknown <android> provider
03-22 13:05:38.284 14966 14989 I python  : [INFO   ] [Base        ] Start application main loop
03-22 13:05:38.322 14966 14989 I python  : [INFO   ] [GL          ] NPOT texture support is available
03-22 13:05:38.443 14966 14999 I python  : ERROR SharedStorage.retrieveUri():
03-22 13:05:38.443 14966 14999 I python  : type object 'android.os.FileUtils' has no attribute 'copy'
03-22 13:05:38.479 14966 14989 I python  : [ERROR  ] [Image       ] Error loading </storage/emulated/0/Android/data/org.test.receive/cache/FromSharedStorage/520ad0643d694cebbd68675ade898942.mp4>
03-22 13:05:38.521 14966 15000 I python  : [WARNING] [ffpyplayer  ] [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7d96591000] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
03-22 13:05:38.523 14966 15000 I python  : [ERROR  ] [ffpyplayer  ] [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7d96591000] moov atom not found
03-22 13:05:38.530 14966 15000 I python  : [ERROR  ] [ffpyplayer  ] /storage/emulated/0/Android/data/org.test.receive/cache/FromSharedStorage/520ad0643d694cebbd68675ade898942.mp4: Invalid data found when processing input

**Comment by RobertFlatt** [comment]
type object 'android.os.FileUtils' has no attribute 'copy'

https://developer.android.com/reference/android/os/FileUtils
min api 29

**Comment by RobertFlatt** [comment]
type object 'android.os.FileUtils' has no attribute 'copy'

https://developer.android.com/reference/android/os/FileUtils
min api 29

There are lost of thing you could try https://www.baeldung.com/convert-input-stream-to-a-file
